### ISSUE TITLE
problems with tetris.exe

### ISSUE THREAD

**Issue by eckopancir** [francopan/tetris_tasm#1]
I welcome, I can’t get a normal exe file, the game does not work, it immediately writes game over. Can you lay out tetris.exe separately?

**Comment by francopan** [comment]
Hello @eckopancir. Indeed, the starting message was wrong. Just updated it. Also, the project is in portuguese, I plan to translate it to english in the future.

Just a reminder, the game is a "work in progress". There are still things missing. I'll update the README to make it clearer.
